version: '3'
services:
  app:
    build: .
    environment:
      MYSQL_HOST: "my_go_app_db"
      MYSQL_DATABASE: "todos-docker"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - ./:/usr/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: "todos-docker"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    container_name: my_go_app_db
    networks:
      - backend
networks:
  backend:
